-- RETIRED: fixed password-reset hashes are unsafe and must never be used.
-- Use the authenticated password-change workflow or a one-time CLI recovery
-- command that accepts a freshly generated secret without committing it.
