<?php
require_once __DIR__.'/../database/config.php';
require_once __DIR__.'/../includes/helpers.php';
require_once __DIR__.'/../services/ReservationService.php';
require_once __DIR__.'/../services/ReservationReminderService.php';
$pass=0;$fail=0;function p7($ok,$name){global$pass,$fail;echo($ok?'PASS':'FAIL').": $name\n";$ok?$pass++:$fail++;}
$users=array_map(fn($r)=>(int)$r['id'],$conn->query("SELECT id FROM users WHERE status='active' ORDER BY id LIMIT 2")->fetch_all(MYSQLI_ASSOC));$resources=array_map(fn($r)=>(int)$r['resource_id'],$conn->query("SELECT resource_id FROM resources WHERE status='available' AND deleted_at IS NULL ORDER BY resource_id LIMIT 2")->fetch_all(MYSQLI_ASSOC));if(count($users)<2||count($resources)<2)exit(2);
[$owner,$other]=$users;[$resource1,$resource2]=$resources;$service=new ReservationService($conn);$reservationId=$requestId=$proposalId=$blockerId=0;$proposalIds=[];$notificationFloor=(int)$conn->query('SELECT COALESCE(MAX(notification_id),0) id FROM notifications')->fetch_assoc()['id'];$auditFloor=(int)$conn->query('SELECT COALESCE(MAX(log_id),0) id FROM audit_log')->fetch_assoc()['id'];
try{
 $created=$service->create($owner,['reservation_type'=>'wedding','start_at'=>'2097-01-10 10:00:00','service_duration_minutes'=>60,'setup_duration_minutes'=>15,'cleanup_duration_minutes'=>15,'event_details'=>'Proposal workflow test','resource_ids'=>[$resource1,$resource2]],hash('sha256',random_bytes(20)));$reservationId=(int)$created['reservation_id'];$requestId=(int)$created['request_id'];$service->changeStatus($reservationId,'approved',$owner,'Approved for proposal testing');
 p7((int)$conn->query("SELECT COUNT(*) c FROM reservation_resources WHERE reservation_id=$reservationId")->fetch_assoc()['c']===2,'multiple resources are assigned to one reservation');
 $proposalId=$service->proposeSchedule($reservationId,['start_at'=>'2097-01-11 14:00:00','service_duration_minutes'=>90,'setup_duration_minutes'=>15,'cleanup_duration_minutes'=>15,'resource_ids'=>[$resource1]],$owner,'Alternative parish schedule','2097-01-10 14:00:00');$proposalIds[]=$proposalId;p7($proposalId>0,'administrator creates a distinct pending proposal');
 $notice=(int)$conn->query("SELECT COUNT(*) c FROM notifications WHERE user_id=$owner AND title='New Schedule Proposal'")->fetch_assoc()['c'];p7($notice>0,'proposal notification is created');
 $unauthorized=false;try{$service->respondToProposal($proposalId,$other,true);}catch(RuntimeException$e){$unauthorized=true;}p7($unauthorized,'another user cannot accept the owner proposal');
 $type='church_venue';$date='2097-01-11';$time='14:15:00';$start='2097-01-11 14:15:00';$end='2097-01-11 14:45:00';$status='pending';$details='Temporary conflict';$stmt=$conn->prepare('INSERT INTO reservations (user_id,reservation_type,event_date,event_time,start_at,end_at,service_duration_minutes,event_details,status) VALUES (?,?,?,?,?,?,30,?,?)');$stmt->bind_param('isssssss',$other,$type,$date,$time,$start,$end,$details,$status);$stmt->execute();$blockerId=$stmt->insert_id;$stmt->close();$stmt=$conn->prepare('INSERT INTO reservation_resources (reservation_id,resource_id) VALUES (?,?)');$stmt->bind_param('ii',$blockerId,$resource1);$stmt->execute();$stmt->close();
 $becameUnavailable=false;try{$service->respondToProposal($proposalId,$owner,true);}catch(DomainException$e){$becameUnavailable=true;}p7($becameUnavailable,'acceptance rechecks resources that became unavailable');$conn->query("UPDATE reservations SET status='cancelled' WHERE reservation_id=$blockerId");
 $service->respondToProposal($proposalId,$owner,true);$row=$conn->query("SELECT start_at,end_at FROM reservations WHERE reservation_id=$reservationId")->fetch_assoc();p7($row['start_at']==='2097-01-11 14:00:00'&&$row['end_at']==='2097-01-11 15:30:00','accepted proposal transactionally reschedules the reservation');
 $history=(int)$conn->query("SELECT COUNT(*) c FROM reservation_schedule_history WHERE reservation_id=$reservationId AND change_type='parishioner_acceptance' AND previous_start_at='2097-01-10 10:00:00'")->fetch_assoc()['c'];p7($history===1,'reschedule history preserves the old schedule');
 $event=$conn->query("SELECT event_date,start_time,status FROM schedule_events WHERE source_type='reservation' AND source_id=$reservationId")->fetch_assoc();p7($event['event_date']==='2097-01-11'&&$event['start_time']==='14:00:00'&&$event['status']==='active','reschedule updates the existing calendar event');
 $oldReminders=(int)$conn->query("SELECT COUNT(*) c FROM reservation_notifications WHERE reservation_id=$reservationId AND scheduled_for IN ('2097-01-09 10:00:00','2097-01-10 08:00:00') AND sent_at IS NULL")->fetch_assoc()['c'];p7($oldReminders===0,'rescheduling removes obsolete unsent reminders');
 $rejectId=$service->proposeSchedule($reservationId,['start_at'=>'2097-01-12 14:00:00','service_duration_minutes'=>90,'resource_ids'=>[$resource1]],$owner,'Second alternative schedule');$proposalIds[]=$rejectId;$service->respondToProposal($rejectId,$owner,false);$rejected=$conn->query("SELECT status FROM schedule_proposals WHERE proposal_id=$rejectId")->fetch_assoc()['status'];p7($rejected==='rejected','parishioner rejection is preserved');
 $expiredId=$service->proposeSchedule($reservationId,['start_at'=>'2097-01-13 14:00:00','service_duration_minutes'=>90,'resource_ids'=>[$resource1]],$owner,'Expiring alternative','2020-01-01 00:00:00');$proposalIds[]=$expiredId;$expired=false;try{$service->respondToProposal($expiredId,$owner,true);}catch(DomainException$e){$expired=true;}p7($expired,'expired proposal cannot be accepted');
 $dueId=(int)$conn->query("SELECT notification_id FROM reservation_notifications WHERE reservation_id=$reservationId AND sent_at IS NULL LIMIT 1")->fetch_assoc()['notification_id'];$conn->query("UPDATE reservation_notifications SET scheduled_for=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE notification_id=$dueId");$runner=new ReservationReminderService($conn);$first=$runner->sendDue();$second=$runner->sendDue();p7($first['sent']===1&&$second['sent']===0,'repeated scheduler execution does not duplicate a reminder');
 $service->changeStatus($reservationId,'cancelled',$owner,'Cancelled after reminder test');$calendarStatus=$conn->query("SELECT status FROM schedule_events WHERE source_type='reservation' AND source_id=$reservationId")->fetch_assoc()['status'];p7($calendarStatus==='cancelled','cancelling a reservation deactivates its linked calendar event');$stmt=$conn->prepare("INSERT IGNORE INTO reservation_notifications (reservation_id,notification_type,scheduled_for) VALUES (?,'cancelled_test',DATE_SUB(NOW(),INTERVAL 1 MINUTE))");$stmt->bind_param('i',$reservationId);$stmt->execute();$stmt->close();p7((new ReservationReminderService($conn))->sendDue()['sent']===0,'cancelled reservations never receive due reminders');
}catch(Throwable$e){echo'FAIL: unexpected proposal/reminder error: '.$e->getMessage()."\n";$fail++;}
finally{
 if($blockerId){$conn->query("DELETE FROM reservation_resources WHERE reservation_id=$blockerId");$conn->query("DELETE FROM reservations WHERE reservation_id=$blockerId");}
 if($reservationId){$proposalList=$proposalIds?implode(',',array_map('intval',$proposalIds)):'0';$conn->query("DELETE FROM notifications WHERE notification_id>$notificationFloor AND user_id IN ($owner,$other)");$conn->query("DELETE FROM audit_log WHERE log_id>$auditFloor AND ((table_name='reservations' AND record_id=$reservationId) OR (table_name='schedule_proposals' AND record_id IN ($proposalList)))");$conn->query("DELETE FROM schedule_events WHERE source_type='reservation' AND source_id=$reservationId");$conn->query("DELETE FROM reservation_notifications WHERE reservation_id=$reservationId");$conn->query("DELETE FROM schedule_proposal_resources WHERE proposal_id IN (SELECT proposal_id FROM schedule_proposals WHERE reservation_id=$reservationId)");$conn->query("DELETE FROM schedule_proposals WHERE reservation_id=$reservationId");$conn->query("DELETE FROM reservation_schedule_history WHERE reservation_id=$reservationId");$conn->query("DELETE FROM reservation_resources WHERE reservation_id=$reservationId");$conn->query("DELETE FROM reservations WHERE reservation_id=$reservationId");}
 if($requestId){$conn->query("DELETE FROM request_status_history WHERE request_id=$requestId");$conn->query("DELETE FROM request_idempotency_keys WHERE request_id=$requestId");$conn->query("DELETE FROM requests WHERE request_id=$requestId");}
}
echo"Phase 7 proposal/reminders: $pass passed, $fail failed.\n";exit($fail?1:0);
