<?php
require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once __DIR__ . '/SacramentalRecordService.php';

use Dompdf\Dompdf;
use Dompdf\Options;
use chillerlan\QRCode\QRCode;

final class CertificateService
{
    private mysqli $db; private string $root;
    private const MAP=[
        'baptism'=>['record_type'=>'baptism','table'=>'baptism_records','id'=>'baptism_id','prefix'=>'BAP'],
        'baptism_certification'=>['record_type'=>'baptism','table'=>'baptism_records','id'=>'baptism_id','prefix'=>'BCF'],
        'communion'=>['record_type'=>'communion','table'=>'first_communion_records','id'=>'communion_id','prefix'=>'COM'],
        'first_communion_certification'=>['record_type'=>'communion','table'=>'first_communion_records','id'=>'communion_id','prefix'=>'FCF'],
        'confirmation'=>['record_type'=>'confirmation','table'=>'confirmation_records','id'=>'confirmation_id','prefix'=>'CON'],
        'confirmation_certification'=>['record_type'=>'confirmation','table'=>'confirmation_records','id'=>'confirmation_id','prefix'=>'CCF'],
        'marriage'=>['record_type'=>'marriage','table'=>'marriage_records','id'=>'marriage_id','prefix'=>'MAR'],
        'marriage_certification'=>['record_type'=>'marriage','table'=>'marriage_records','id'=>'marriage_id','prefix'=>'MCF'],
        'funeral_certification'=>['record_type'=>'funeral','table'=>'funeral_records','id'=>'funeral_id','prefix'=>'FNC'],
    ];
    public function __construct(mysqli$db,string$root){$this->db=$db;$this->root=rtrim($root,'/\\');}

    public function draft(string$type,int$recordId,?int$requestId,int$actor):int
    {
        $m=$this->meta($type);$record=$this->record($m,$recordId,false);if(($record['status']??'active')!=='active')throw new DomainException('Certificates cannot be drafted from an archived record.');$stmt=$this->db->prepare("SELECT certificate_id FROM certificate_issuances WHERE certificate_type=? AND record_table=? AND record_id=? AND status<>'revoked' ORDER BY certificate_id DESC LIMIT 1");$stmt->bind_param('ssi',$type,$m['table'],$recordId);$stmt->execute();$existing=$stmt->get_result()->fetch_assoc();$stmt->close();if($existing)throw new DomainException('An active certificate workflow already exists for this record (certificate #'.(int)$existing['certificate_id'].'). Revoke it before reissue.');
        $linked=$record['request_id']? (int)$record['request_id']:null;if($requestId&&$linked!==$requestId)throw new DomainException('The certificate request does not match the record linkage.');$requestId=$requestId?:$linked;
        if($requestId){$stmt=$this->db->prepare("SELECT status FROM requests WHERE request_id=? AND deleted_at IS NULL");$stmt->bind_param('i',$requestId);$stmt->execute();$r=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$r||!in_array($r['status'],['approved','scheduled','processing','ready_for_release','completed'],true))throw new DomainException('The linked request is not approved for certificate processing.');}
        $name=$this->subject($record);$layout=function_exists('getCertificateLayout')?getCertificateLayout($this->db,$type):['settings'=>[]];$layoutJson=json_encode($layout['settings']??[],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
        $stmt=$this->db->prepare("INSERT INTO certificate_issuances(request_id,certificate_type,record_table,record_id,layout_snapshot,drafted_by,drafted_at,issued_to,status,issued_at) VALUES(?,?,?,?,?,?,NOW(),?,'draft',NULL)");$stmt->bind_param('issiiss',$requestId,$type,$m['table'],$recordId,$layoutJson,$actor,$name);$stmt->execute();$id=(int)$stmt->insert_id;$stmt->close();$this->event($id,$requestId,$actor,'drafted');return$id;
    }
    public function advance(int$id,string$action,int$actor,string$reason=''):void
    {
        $map=['submit_review'=>['draft','review','reviewed_by','reviewed_at','reviewed'],'approve'=>['review','approval','approved_by','approved_at','approved'],'release'=>['issued','released','released_by','released_at','released']];if(!isset($map[$action]))throw new DomainException('Invalid certificate action.');[$from,$to,$actorCol,$dateCol,$event]=$map[$action];$this->db->begin_transaction();try{$c=$this->certificate($id,true);if($c['status']!==$from)throw new DomainException('Certificate is not in the required '.$from.' state.');if($action==='release'&&(empty($c['pdf_path'])||empty($c['certificate_hash'])))throw new DomainException('Legacy certificates without an immutable PDF and hash cannot be released. Revoke and reissue through the controlled workflow.');$stmt=$this->db->prepare("UPDATE certificate_issuances SET status=?,`$actorCol`=?,`$dateCol`=NOW() WHERE certificate_id=?");$stmt->bind_param('sii',$to,$actor,$id);$stmt->execute();$stmt->close();$this->event($id,$c['request_id']?(int)$c['request_id']:null,$actor,$event,$reason);$this->db->commit();}catch(Throwable$e){$this->db->rollback();throw$e;}
    }
    public function issue(int$id,int$actor):array
    {
        $final=null;$this->db->begin_transaction();try{$c=$this->certificate($id,true);if($c['status']!=='approval'||empty($c['approved_at']))throw new DomainException('Only an approved certificate can be issued.');$m=$this->meta($c['certificate_type']);$record=$this->record($m,(int)$c['record_id'],true);if(($record['status']??'active')!=='active')throw new DomainException('The source record is archived.');$number=$this->nextNumber($m['prefix']);$token=bin2hex(random_bytes(32));$snapshot=['schema'=>1,'certificate_type'=>$c['certificate_type'],'certificate_number'=>$number,'issued_at'=>date(DATE_ATOM),'issued_to'=>$this->subject($record),'record'=>$record,'layout'=>json_decode($c['layout_snapshot']?:'{}',true)];$json=json_encode($snapshot,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$pdf=$this->renderPdf($snapshot,$token);$hash=hash('sha256',$pdf);$dir=$this->root.DIRECTORY_SEPARATOR.'uploads'.DIRECTORY_SEPARATOR.'issued_certificates';if(!is_dir($dir)&&!mkdir($dir,0750,true))throw new RuntimeException('Unable to create protected certificate storage.');$relative='uploads/issued_certificates/'.preg_replace('/[^A-Z0-9-]/','',$number).'.pdf';$final=$this->root.DIRECTORY_SEPARATOR.str_replace('/',DIRECTORY_SEPARATOR,$relative);$temp=$final.'.'.bin2hex(random_bytes(5)).'.tmp';if(file_put_contents($temp,$pdf,LOCK_EX)===false||!rename($temp,$final))throw new RuntimeException('Unable to write the issued PDF.');$stmt=$this->db->prepare("UPDATE certificate_issuances SET status='issued',certificate_number=?,verification_code=?,certificate_snapshot=?,pdf_path=?,certificate_hash=?,issued_by=?,issued_at=NOW() WHERE certificate_id=?");$stmt->bind_param('sssssii',$number,$token,$json,$relative,$hash,$actor,$id);if(!$stmt->execute())throw new RuntimeException('Unable to persist certificate issuance: '.$stmt->error);$stmt->close();(new SacramentalRecordService($this->db))->lock($m['record_type'],(int)$c['record_id'],$actor,'Official certificate '.$number.' issued.');$this->event($id,$c['request_id']?(int)$c['request_id']:null,$actor,'issued','Final issuance confirmed',['sha256'=>$hash,'certificate_number'=>$number]);$this->db->commit();return['number'=>$number,'hash'=>$hash,'path'=>$relative,'token'=>$token];}catch(Throwable$e){$this->db->rollback();if($final&&is_file($final))@unlink($final);throw$e;}
    }
    public function revoke(int$id,string$reason,int$actor):void {if(strlen(trim($reason))<5)throw new DomainException('A revocation reason of at least five characters is required.');$this->db->begin_transaction();try{$c=$this->certificate($id,true);if(!in_array($c['status'],['issued','released'],true))throw new DomainException('Only issued or released certificates may be revoked.');$stmt=$this->db->prepare("UPDATE certificate_issuances SET status='revoked',revoked_by=?,revoked_at=NOW(),revocation_reason=? WHERE certificate_id=?");$stmt->bind_param('isi',$actor,$reason,$id);$stmt->execute();$stmt->close();$this->event($id,$c['request_id']?(int)$c['request_id']:null,$actor,'revoked',$reason);$this->db->commit();}catch(Throwable$e){$this->db->rollback();throw$e;}}
    public function reissue(int$id,string$reason,int$actor):int {if(strlen(trim($reason))<5)throw new DomainException('A reissue reason is required.');$old=$this->certificate($id,false);if($old['status']!=='revoked')throw new DomainException('Reissue is available only after revocation.');$new=$this->draft($old['certificate_type'],(int)$old['record_id'],$old['request_id']?(int)$old['request_id']:null,$actor);$stmt=$this->db->prepare('UPDATE certificate_issuances SET original_certificate_id=?,reissue_reason=?,reissue_requested_by=? WHERE certificate_id=?');$stmt->bind_param('isii',$id,$reason,$actor,$new);$stmt->execute();$stmt->close();$this->event($new,$old['request_id']?(int)$old['request_id']:null,$actor,'reissued',$reason,['original_certificate_id'=>$id]);return$new;}
    public function logDownload(int$id,int$actor):void{$c=$this->certificate($id,false);$this->event($id,$c['request_id']?(int)$c['request_id']:null,$actor,'downloaded');}
    private function renderPdf(array$s,string$token):string{$url=$this->baseUrl().'verify-certificate.php?code='.rawurlencode($token);$qr=(new QRCode)->render($url);$record=$s['record'];$details='';foreach($record as$k=>$v){if($v===null||in_array($k,['duplicate_fingerprint','locked_by','archived_by','restored_by'],true))continue;$details.='<tr><th>'.htmlspecialchars(ucwords(str_replace('_',' ',$k))).'</th><td>'.htmlspecialchars((string)$v).'</td></tr>';}$html='<!doctype html><html><head><meta charset="utf-8"><style>@page{margin:28px}body{font-family:DejaVu Sans;color:#192033;border:5px double #b88a22;padding:30px}h1{text-align:center;color:#8a681c}h2{text-align:center}table{width:100%;border-collapse:collapse;margin:20px 0}th,td{padding:6px;border-bottom:1px solid #ddd;text-align:left;font-size:11px}.verify{text-align:center;margin-top:20px}.verify img{width:120px;height:120px}.hash{font-size:8px;word-break:break-all}</style></head><body><h2>SAN LORENZO RUIZ MISSION STATION</h2><h1>'.htmlspecialchars(strtoupper(str_replace('_',' ',$s['certificate_type']))).'</h1><p style="text-align:center"><strong>'.htmlspecialchars($s['certificate_number']).'</strong></p><p>This certifies that <strong>'.htmlspecialchars($s['issued_to']).'</strong> appears in the official parish record.</p><table>'.$details.'</table><div class="verify"><img src="'.$qr.'"><p>Scan to verify<br>'.htmlspecialchars($url).'</p></div><p>Issued '.htmlspecialchars($s['issued_at']).'</p></body></html>';$options=new Options();$options->set('isRemoteEnabled',false);$dompdf=new Dompdf($options);$dompdf->loadHtml($html,'UTF-8');$dompdf->setPaper('A4','portrait');$dompdf->render();return$dompdf->output();}
    private function nextNumber(string$prefix):string{$year=(int)date('Y');for($attempt=0;$attempt<100;$attempt++){$stmt=$this->db->prepare('INSERT INTO certificate_number_sequences(sequence_year,prefix,next_number) VALUES(?,?,1) ON DUPLICATE KEY UPDATE next_number=LAST_INSERT_ID(next_number+1)');$stmt->bind_param('is',$year,$prefix);$stmt->execute();$n=$stmt->insert_id?(int)$stmt->insert_id:1;$stmt->close();$number=sprintf('%s-%d-%06d',$prefix,$year,$n);$stmt=$this->db->prepare('SELECT 1 FROM certificate_issuances WHERE certificate_number=?');$stmt->bind_param('s',$number);$stmt->execute();$exists=(bool)$stmt->get_result()->fetch_row();$stmt->close();if(!$exists)return$number;}throw new RuntimeException('Unable to allocate a unique certificate number.');}
    private function meta(string$type):array{if(!isset(self::MAP[$type]))throw new DomainException('Unsupported certificate type.');return self::MAP[$type];}
    private function record(array$m,int$id,bool$lock):array{$stmt=$this->db->prepare('SELECT * FROM `'.$m['table'].'` WHERE `'.$m['id'].'`=?'.($lock?' FOR UPDATE':''));$stmt->bind_param('i',$id);$stmt->execute();$r=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$r)throw new DomainException('Source record not found.');return$r;}
    private function certificate(int$id,bool$lock):array{$stmt=$this->db->prepare('SELECT * FROM certificate_issuances WHERE certificate_id=?'.($lock?' FOR UPDATE':''));$stmt->bind_param('i',$id);$stmt->execute();$r=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$r)throw new DomainException('Certificate not found.');return$r;}
    private function subject(array$r):string{return trim((string)($r['fullname']??$r['deceased_name']??trim(($r['husband_name']??'').' and '.($r['wife_name']??''))));}
    private function event(int$id,?int$request,int$actor,string$action,string$reason='',array$meta=[]):void{$json=$meta?json_encode($meta,JSON_UNESCAPED_SLASHES):null;$stmt=$this->db->prepare('INSERT INTO certificate_events(certificate_id,request_id,actor_user_id,action,reason,metadata_json) VALUES(?,?,?,?,?,?)');$stmt->bind_param('iiisss',$id,$request,$actor,$action,$reason,$json);$stmt->execute();$stmt->close();}
    private function baseUrl():string{return rtrim(appUrl(),'/').'/';}
}
