<?php
final class NotificationService
{
    private mysqli $db;
    private const ACTIONS=['request.view'=>'my-requests.php','reservation.view'=>'view-schedule.php','announcement.view'=>'announcements.php','certificate.view'=>'my-requests.php','account.view'=>'profile.php'];
    private const CATEGORIES=['request_submitted'=>'requests','request_approved'=>'requests','request_rejected'=>'requests','reservation_created'=>'schedules','reservation_approved'=>'schedules','reservation_rescheduled'=>'schedules','reservation_cancelled'=>'schedules','reservation_reminder'=>'schedules','certificate_ready'=>'requests','certificate_released'=>'requests','announcement_published'=>'announcements'];
    public function __construct(mysqli$db){$this->db=$db;}
    public static function actionUrl(?string$key):string{return self::ACTIONS[$key??'']??'index.php';}
    public function create(int$userId,string$type,array$variables=[],?string$entityType=null,?int$entityId=null,?string$actionKey=null,?string$dedupeSeed=null,bool$outbound=true):?int
    {
        if($userId<=0)throw new DomainException('Notification recipient is required.');if($actionKey!==null&&!isset(self::ACTIONS[$actionKey]))throw new DomainException('Unsupported notification action.');
        $stmt=$this->db->prepare("SELECT * FROM notification_templates WHERE notification_type=? AND status='active'");$stmt->bind_param('s',$type);$stmt->execute();$tpl=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$tpl)throw new DomainException('Unknown notification type: '.$type);
        $title=$this->render($tpl['title_template'],$variables);$message=$this->render($tpl['in_app_template'],$variables);$dedupe=$dedupeSeed!==null?hash('sha256',$type.'|'.$entityType.'|'.$entityId.'|'.$dedupeSeed):null;
        $stmt=$this->db->prepare("INSERT IGNORE INTO notifications(user_id,notification_type,title,message,entity_type,entity_id,action_key,state,deduplication_key,is_read) VALUES(?,?,?,?,?,?,?,'unread',?,0)");$stmt->bind_param('issssiss',$userId,$type,$title,$message,$entityType,$entityId,$actionKey,$dedupe);$stmt->execute();$id=(int)$stmt->insert_id;$stmt->close();if(!$id)return null;
        $category=self::CATEGORIES[$type]??'system';foreach(['in_app','email','sms']as$channel){$allowed=$channel==='in_app'||($outbound&&$this->allows($userId,$category,$channel));$status=$allowed?($channel==='in_app'?'sent':'pending'):'cancelled';$idempotency=hash('sha256',$id.'|'.$channel.'|'.$userId.'|1');$stmt=$this->db->prepare('INSERT INTO notification_deliveries(notification_id,channel,idempotency_key,status,attempt_count,sent_at,next_attempt_at) VALUES(?,?,?,?,0,IF(?=\'sent\',NOW(),NULL),IF(?=\'pending\',NOW(),NULL))');$stmt->bind_param('isssss',$id,$channel,$idempotency,$status,$status,$status);$stmt->execute();$stmt->close();}
        return$id;
    }
    public function createLegacy(int$userId,string$title,string$message,bool$outbound=true,string$category='system'):?int{$stmt=$this->db->prepare("INSERT INTO notifications(user_id,notification_type,title,message,state,is_read) VALUES(?,'system',?,?,'unread',0)");$stmt->bind_param('iss',$userId,$title,$message);$stmt->execute();$id=(int)$stmt->insert_id;$stmt->close();if(!$id)return null;foreach(['in_app','email','sms']as$channel){$allowed=$channel==='in_app'||($outbound&&$this->allows($userId,$category,$channel));$status=$allowed?($channel==='in_app'?'sent':'pending'):'cancelled';$key=hash('sha256',$id.'|'.$channel.'|'.$userId.'|1');$stmt=$this->db->prepare("INSERT INTO notification_deliveries(notification_id,channel,idempotency_key,status,attempt_count,sent_at,next_attempt_at) VALUES(?,?,?,?,0,IF(?='sent',NOW(),NULL),IF(?='pending',NOW(),NULL))");$stmt->bind_param('isssss',$id,$channel,$key,$status,$status,$status);$stmt->execute();$stmt->close();}return$id;}
    public function transition(int$id,int$userId,string$state):void{if(!in_array($state,['read','archived','deleted'],true))throw new DomainException('Invalid notification state.');$date=['read'=>'read_at','archived'=>'archived_at','deleted'=>'deleted_at'][$state];$read=$state==='read'?1:0;$stmt=$this->db->prepare("UPDATE notifications SET state=?,is_read=IF(?='read',1,is_read),`$date`=NOW() WHERE notification_id=? AND user_id=? AND state<>'deleted'");$stmt->bind_param('ssii',$state,$state,$id,$userId);$stmt->execute();$stmt->close();}
    public function markAllRead(int$userId):void{$stmt=$this->db->prepare("UPDATE notifications SET state='read',is_read=1,read_at=COALESCE(read_at,NOW()) WHERE user_id=? AND state='unread'");$stmt->bind_param('i',$userId);$stmt->execute();$stmt->close();}
    public function retry(int$deliveryId):void{$stmt=$this->db->prepare("SELECT d.*,n.user_id,n.notification_type,n.title,n.message FROM notification_deliveries d JOIN notifications n ON n.notification_id=d.notification_id WHERE d.delivery_id=? AND d.status IN('failed','pending') AND d.attempt_count<5");$stmt->bind_param('i',$deliveryId);$stmt->execute();$row=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$row)throw new DomainException('No retryable delivery was found.');$channel=$row['channel'];if($channel==='in_app'){$status='sent';$failure=null;}else{$category=self::CATEGORIES[$row['notification_type']]??'system';$channels=['email'=>false,'sms'=>false];$channels[$channel]=true;$result=dispatchNotificationDelivery($this->db,(int)$row['user_id'],$row['title'],$row['message'],$category,$channels);$attempt=$result[$channel]??[];$status=!empty($attempt['ok'])&&!empty($attempt['skipped'])?'cancelled':(!empty($attempt['ok'])?'sent':'failed');$failure=$attempt['error']??null;}$delay=min(3600,60*(2**(int)$row['attempt_count']));$stmt=$this->db->prepare("UPDATE notification_deliveries SET status=?,attempt_count=attempt_count+1,last_attempt_at=NOW(),next_attempt_at=IF(?='failed',DATE_ADD(NOW(),INTERVAL ? SECOND),NULL),sent_at=IF(?='sent',NOW(),sent_at),failed_at=IF(?='failed',NOW(),failed_at),failure_reason=? WHERE delivery_id=?");$stmt->bind_param('ssisssi',$status,$status,$delay,$status,$status,$failure,$deliveryId);$stmt->execute();$stmt->close();}
    private function render(string$template,array$vars):string{return preg_replace_callback('/{{([a-zA-Z0-9_]+)}}/',function($m)use($vars){return array_key_exists($m[1],$vars)?trim(strip_tags((string)$vars[$m[1]])):'—';},$template);}
    private function allows(int$user,string$category,string$channel):bool{$column=$channel==='sms'?'sms_enabled':'email_enabled';$stmt=$this->db->prepare("SELECT `$column` enabled FROM notification_preferences WHERE user_id=? AND category=?");$stmt->bind_param('is',$user,$category);$stmt->execute();$row=$stmt->get_result()->fetch_assoc();$stmt->close();return !$row||(int)$row['enabled']===1;}
}
