<?php
include '../includes/session.php';
include '../database/config.php';
include '../includes/helpers.php';
requireAdmin();requirePermission('reservations.manage');
$error='';$success='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    requireValidCsrfToken();$action=$_POST['action']??'';
    try{
        if($action==='save_resource'){
            $id=(int)($_POST['resource_id']??0);$type=trim((string)($_POST['resource_type']??''));$name=trim((string)($_POST['name']??''));$description=trim((string)($_POST['description']??''));$location=trim((string)($_POST['location']??''));$capacity=($_POST['capacity']??'')===''?null:(int)$_POST['capacity'];$status=trim((string)($_POST['status']??'available'));
            if(!in_array($type,['area','chapel','hall','priest','staff','equipment'],true)||!in_array($status,['available','unavailable','maintenance','archived'],true)||$name==='')throw new InvalidArgumentException('Enter a valid resource name, type, and status.');
            if($id){$stmt=$conn->prepare('UPDATE resources SET resource_type=?,name=?,description=?,location=?,capacity=?,status=? WHERE resource_id=? AND deleted_at IS NULL');$stmt->bind_param('ssssisi',$type,$name,$description,$location,$capacity,$status,$id);}else{$stmt=$conn->prepare('INSERT INTO resources (resource_type,name,description,location,capacity,status) VALUES (?,?,?,?,?,?)');$stmt->bind_param('ssssis',$type,$name,$description,$location,$capacity,$status);}$stmt->execute();$recordId=$id?:$stmt->insert_id;$stmt->close();createAuditLog($conn,(int)$_SESSION['user_id'],'SAVE_RESOURCE','resources',$recordId);$success='Resource saved.';
        }elseif($action==='add_blackout'){
            $resourceId=(int)($_POST['resource_id']??0);$start=str_replace('T',' ',trim((string)($_POST['start_at']??''))).':00';$end=str_replace('T',' ',trim((string)($_POST['end_at']??''))).':00';$reason=trim((string)($_POST['reason']??''));$rule=trim((string)($_POST['recurrence_rule']??''));if($resourceId<=0||strtotime($end)<=strtotime($start)||mb_strlen($reason)<5)throw new InvalidArgumentException('Enter a valid blackout interval and reason.');if($rule!==''&&!preg_match('/^(weekly:[0-6]|annual:\d{2}-\d{2})$/',$rule))throw new InvalidArgumentException('Recurrence must be weekly:0 through weekly:6, annual:MM-DD, or blank.');$actor=(int)$_SESSION['user_id'];$stmt=$conn->prepare('INSERT INTO resource_unavailability (resource_id,start_at,end_at,reason,recurrence_rule,created_by) VALUES (?,?,?,?,NULLIF(?,\'\'),?)');$stmt->bind_param('issssi',$resourceId,$start,$end,$reason,$rule,$actor);$stmt->execute();$id=$stmt->insert_id;$stmt->close();createAuditLog($conn,$actor,'CREATE_RESOURCE_BLACKOUT','resource_unavailability',$id);$success='Resource blackout saved.';
        }elseif($action==='archive_resource'){$id=(int)($_POST['resource_id']??0);$stmt=$conn->prepare("UPDATE resources SET status='archived',deleted_at=NOW() WHERE resource_id=?");$stmt->bind_param('i',$id);$stmt->execute();$stmt->close();createAuditLog($conn,(int)$_SESSION['user_id'],'ARCHIVE_RESOURCE','resources',$id);$success='Resource archived.';}
    }catch(Throwable $e){$error=$e->getMessage();}
}
$resources=$conn->query('SELECT * FROM resources WHERE deleted_at IS NULL ORDER BY resource_type,name')->fetch_all(MYSQLI_ASSOC);
$blackouts=$conn->query('SELECT u.*,r.name resource_name FROM resource_unavailability u JOIN resources r ON r.resource_id=u.resource_id ORDER BY u.start_at DESC LIMIT 100')->fetch_all(MYSQLI_ASSOC);
$page_title='Manage Resources';
$breadcrumbs = [
    'Dashboard' => 'dashboard.php',
    'Reservations' => 'manage-reservations.php',
    'Manage Resources' => null
];
include '../templates/header.php';
?>
<div class="container-fluid px-0">
    <!-- Standardized Section Header -->
    <?php
    $page_header_title = 'Reservation Resources';
    $page_header_subtitle = 'Manage parish facilities, personnel, equipment, and blackout scheduling.';
    $page_header_icon = 'fa-warehouse';
    $show_back_button = true;
    $back_button_url = 'manage-reservations.php';
    include '../includes/page_header.php';
    ?>
<?php if($error):?><div class="alert alert-danger"><?php echo e($error);?></div><?php endif;?><?php if($success):?><div class="alert alert-success"><?php echo e($success);?></div><?php endif;?>
<div class="row g-4"><div class="col-lg-6"><div class="card"><div class="card-header">Add resource</div><div class="card-body"><form method="POST"><?php echo csrfInput();?><input type="hidden" name="action" value="save_resource"><div class="row g-2"><div class="col-md-6"><label class="form-label">Name</label><input class="form-control" name="name" maxlength="150" required></div><div class="col-md-6"><label class="form-label">Type</label><select class="form-select" name="resource_type"><?php foreach(['area','chapel','hall','priest','staff','equipment'] as$type):?><option><?php echo e($type);?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label">Location</label><input class="form-control" name="location"></div><div class="col-md-3"><label class="form-label">Capacity</label><input class="form-control" type="number" min="0" name="capacity"></div><div class="col-md-3"><label class="form-label">Status</label><select class="form-select" name="status"><option>available</option><option>unavailable</option><option>maintenance</option></select></div><div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description" maxlength="500"></textarea></div></div><button class="btn btn-primary mt-3">Save resource</button></form></div></div></div>
<div class="col-lg-6"><div class="card"><div class="card-header">Add blackout</div><div class="card-body"><form method="POST"><?php echo csrfInput();?><input type="hidden" name="action" value="add_blackout"><label class="form-label">Resource</label><select class="form-select mb-2" name="resource_id" required><?php foreach($resources as$r):?><option value="<?php echo(int)$r['resource_id'];?>"><?php echo e($r['name']);?></option><?php endforeach;?></select><div class="row"><div class="col"><label class="form-label">Start</label><input class="form-control" type="datetime-local" name="start_at" required></div><div class="col"><label class="form-label">End</label><input class="form-control" type="datetime-local" name="end_at" required></div></div><label class="form-label mt-2">Reason</label><input class="form-control" name="reason" minlength="5" required><label class="form-label mt-2">Recurrence (optional)</label><input class="form-control" name="recurrence_rule" placeholder="weekly:0 or annual:12-25"><button class="btn btn-primary mt-3">Save blackout</button></form></div></div></div></div>
<div class="card mt-4"><div class="card-header">Active resources</div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Name</th><th>Type</th><th>Location</th><th>Capacity</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($resources as$r):?><tr><td><?php echo e($r['name']);?></td><td><?php echo e($r['resource_type']);?></td><td><?php echo e($r['location']);?></td><td><?php echo e($r['capacity']??'—');?></td><td><?php echo e($r['status']);?></td><td><div class="d-flex gap-2"><button type="button" class="btn btn-sm btn-outline-primary edit-resource" data-bs-toggle="modal" data-bs-target="#editResourceModal" data-resource='<?php echo e(json_encode($r,JSON_HEX_APOS|JSON_HEX_QUOT));?>'>Edit</button><form method="POST" onsubmit="return confirm('Archive this resource? Existing reservations will retain it.');"><?php echo csrfInput();?><input type="hidden" name="action" value="archive_resource"><input type="hidden" name="resource_id" value="<?php echo(int)$r['resource_id'];?>"><button class="btn btn-sm btn-outline-danger">Archive</button></form></div></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="card mt-4"><div class="card-header">Blackout history</div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Resource</th><th>Start</th><th>End</th><th>Recurrence</th><th>Reason</th></tr></thead><tbody><?php foreach($blackouts as$b):?><tr><td><?php echo e($b['resource_name']);?></td><td><?php echo e($b['start_at']);?></td><td><?php echo e($b['end_at']);?></td><td><?php echo e($b['recurrence_rule']?:'None');?></td><td><?php echo e($b['reason']);?></td></tr><?php endforeach;?></tbody></table></div></div></div>
<div class="modal fade" id="editResourceModal" tabindex="-1"><div class="modal-dialog"><form class="modal-content" method="POST"><?php echo csrfInput();?><input type="hidden" name="action" value="save_resource"><input type="hidden" name="resource_id" id="editResourceId"><div class="modal-header"><h5 class="modal-title">Edit resource</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Name</label><input class="form-control" id="editResourceName" name="name" required><label class="form-label mt-2">Type</label><select class="form-select" id="editResourceType" name="resource_type"><?php foreach(['area','chapel','hall','priest','staff','equipment']as$type):?><option><?php echo e($type);?></option><?php endforeach;?></select><label class="form-label mt-2">Location</label><input class="form-control" id="editResourceLocation" name="location"><label class="form-label mt-2">Capacity</label><input class="form-control" id="editResourceCapacity" type="number" min="0" name="capacity"><label class="form-label mt-2">Status</label><select class="form-select" id="editResourceStatus" name="status"><option>available</option><option>unavailable</option><option>maintenance</option><option>archived</option></select><label class="form-label mt-2">Description</label><textarea class="form-control" id="editResourceDescription" name="description"></textarea></div><div class="modal-footer"><button class="btn btn-primary">Save changes</button></div></form></div></div>
<script>document.querySelectorAll('.edit-resource').forEach(function(button){button.addEventListener('click',function(){const r=JSON.parse(button.dataset.resource);document.getElementById('editResourceId').value=r.resource_id;document.getElementById('editResourceName').value=r.name||'';document.getElementById('editResourceType').value=r.resource_type;document.getElementById('editResourceLocation').value=r.location||'';document.getElementById('editResourceCapacity').value=r.capacity||'';document.getElementById('editResourceStatus').value=r.status;document.getElementById('editResourceDescription').value=r.description||'';});});</script>
<?php include '../templates/footer.php';?>
