<?php
require_once '../includes/session.php';require_once '../database/config.php';require_once '../includes/helpers.php';require_once '../services/NotificationService.php';requireLogin();requirePermission('notifications.retry');
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){requireValidCsrfToken();try{(new NotificationService($conn))->retry((int)($_POST['delivery_id']??0));redirectWithNotification('notification-deliveries.php','Delivery attempt completed.','success');}catch(Throwable$e){redirectWithNotification('notification-deliveries.php',$e->getMessage(),'error');}}
$page=max(1,(int)($_GET['page']??1));$perPage=50;$offset=($page-1)*$perPage;$status=in_array($_GET['status']??'', ['pending','failed'],true)?$_GET['status']:'';$channel=in_array($_GET['channel']??'', ['email','sms'],true)?$_GET['channel']:'';$where=["d.status IN('failed','pending')"];$types='';$params=[];if($status){$where[]='d.status=?';$types.='s';$params[]=$status;}if($channel){$where[]='d.channel=?';$types.='s';$params[]=$channel;}$whereSql=implode(' AND ',$where);
$count=$conn->prepare("SELECT COUNT(*) c FROM notification_deliveries d WHERE $whereSql");if($types)$count->bind_param($types,...$params);$count->execute();$total=(int)($count->get_result()->fetch_assoc()['c']??0);$count->close();$pages=max(1,(int)ceil($total/$perPage));
$stmt=$conn->prepare("SELECT d.*,n.notification_type,n.title,u.fullname FROM notification_deliveries d JOIN notifications n ON n.notification_id=d.notification_id JOIN users u ON u.id=n.user_id WHERE $whereSql ORDER BY COALESCE(d.next_attempt_at,d.last_attempt_at),d.delivery_id LIMIT ? OFFSET ?");$bindTypes=$types.'ii';$bind=array_merge($params,[$perPage,$offset]);$stmt->bind_param($bindTypes,...$bind);$stmt->execute();$rows=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);$stmt->close();$page_title='Notification Deliveries';include '../templates/header.php';
?>
<div class="container-fluid px-0">
  <!-- Standardized Section Header -->
  <?php
  $page_header_title = 'Notification Delivery Queue';
  $page_header_subtitle = 'Queued email and SMS attempts with bounded retries and idempotency protection.';
  $page_header_icon = 'fa-paper-plane';
  $show_back_button = true;
  $back_button_url = BASE_URL . 'admin/dashboard.php';
  include '../includes/page_header.php';
  ?>
<form class="card card-body mb-3" method="get"><div class="row g-3 align-items-end"><div class="col-sm-4"><label for="deliveryStatus" class="form-label">Status</label><select id="deliveryStatus" name="status" class="form-select"><option value="">Pending and failed</option><option value="pending" <?php echo $status==='pending'?'selected':''; ?>>Pending</option><option value="failed" <?php echo $status==='failed'?'selected':''; ?>>Failed</option></select></div><div class="col-sm-4"><label for="deliveryChannel" class="form-label">Channel</label><select id="deliveryChannel" name="channel" class="form-select"><option value="">Email and SMS</option><option value="email" <?php echo $channel==='email'?'selected':''; ?>>Email</option><option value="sms" <?php echo $channel==='sms'?'selected':''; ?>>SMS</option></select></div><div class="col-sm-4 d-grid"><button class="btn btn-primary">Apply filters</button></div></div></form>
<div class="card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Recipient</th><th>Type</th><th>Channel</th><th>Status</th><th>Attempts</th><th>Next attempt</th><th>Error</th><th>Action</th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="8" class="text-center py-5">No pending or failed deliveries.</td></tr><?php endif; ?><?php foreach($rows as$r):?><tr><td><?php echo e($r['fullname']);?></td><td><?php echo e($r['notification_type']);?></td><td><?php echo e($r['channel']);?></td><td><span class="badge <?php echo $r['status']==='failed'?'bg-danger':'bg-warning text-dark'; ?>"><i class="fas fa-circle-info" aria-hidden="true"></i> <?php echo e(ucfirst($r['status']));?></span></td><td><?php echo(int)$r['attempt_count'];?> / 5</td><td><?php echo e($r['next_attempt_at']?:'Ready'); ?></td><td><?php echo e(mb_strimwidth((string)$r['failure_reason'],0,120,'...'));?></td><td><?php if((int)$r['attempt_count']<5):?><form method="post" data-confirm="Retry this delivery now? The idempotency key prevents duplicate queue records."><?php echo csrfInput();?><input type="hidden" name="delivery_id" value="<?php echo(int)$r['delivery_id'];?>"><button class="btn btn-sm btn-primary">Retry</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div>
<?php if($pages>1): ?><nav class="mt-3" aria-label="Delivery pages"><ul class="pagination"><?php for($p=max(1,$page-2);$p<=min($pages,$page+2);$p++): ?><li class="page-item <?php echo $p===$page?'active':''; ?>"><a class="page-link" href="?<?php echo e(http_build_query(['status'=>$status,'channel'=>$channel,'page'=>$p])); ?>"><?php echo $p; ?></a></li><?php endfor; ?></ul></nav><?php endif; ?></div>
<?php include '../templates/footer.php'; ?>
